insert into State values ('NY','New York');
insert into State values ('PR','Puerto Rico');
insert into State values ('VI','Virgin Islands');
insert into State values ('MA','Massachusetts');
insert into State values ('RI','Rhode Island');
insert into State values ('NH','New Hampshire');
insert into State values ('ME','Maine');
insert into State values ('VT','Vermont');
insert into State values ('CT','Connecticut');
insert into State values ('NJ','New Jersey');
insert into State values ('AE','U.S. Armed Forces – Europe');
insert into State values ('PA','Pennsylvania');
insert into State values ('DE','Delaware');
insert into State values ('VA','Virginia');
insert into State values ('DC','District of Columbia');
insert into State values ('MD','Maryland');
insert into State values ('WV','West Virginia');
insert into State values ('NC','North Carolina');
insert into State values ('SC','South Carolina');
insert into State values ('GA','Georgia');
insert into State values ('FL','Florida');
insert into State values ('AA','U.S. Armed Forces – Americas');
insert into State values ('AL','Alabama');
insert into State values ('TN','Tennessee');
insert into State values ('MS','Mississippi');
insert into State values ('KY','Kentucky');
insert into State values ('OH','Ohio');
insert into State values ('IN','Indiana');
insert into State values ('MI','Michigan');
insert into State values ('IA','Iowa');
insert into State values ('WI','Wisconsin');
insert into State values ('MN','Minnesota');
insert into State values ('SD','South Dakota');
insert into State values ('ND','North Dakota');
insert into State values ('MT','Montana');
insert into State values ('IL','Illinois');
insert into State values ('MO','Missouri');
insert into State values ('KS','Kansas');
insert into State values ('NE','Nebraska');
insert into State values ('LA','Louisiana');
insert into State values ('AR','Arkansas');
insert into State values ('OK','Oklahoma');
insert into State values ('TX','Texas');
insert into State values ('CO','Colorado');
insert into State values ('WY','Wyoming');
insert into State values ('ID','Idaho');
insert into State values ('UT','Utah');
insert into State values ('AZ','Arizona');
insert into State values ('NM','New Mexico');
insert into State values ('NV','Nevada');
insert into State values ('CA','California');
insert into State values ('AP','U.S. Armed Forces – Pacific');
insert into State values ('HI','Hawaii');
insert into State values ('AS','American Samoa');
insert into State values ('GU','Guam');
insert into State values ('PW','Palau');
insert into State values ('FM','Micronesia');
insert into State values ('MP','Northern Mariana Islands');
insert into State values ('MH','Marshall Islands');
insert into State values ('OR','Oregon');
insert into State values ('WA','Washington');
insert into State values ('AK','Alaska');
